# Generated by Django 4.2.6 on 2024-01-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered',
            field=models.BooleanField(null=True),
        ),
    ]
