# Generated by Django 4.2.6 on 2024-01-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_user_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
    ]
