# Generated by Django 4.2.6 on 2024-04-09 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_alter_otp_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
