# Generated by Django 4.2.6 on 2024-04-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
