# Generated by Django 4.2.6 on 2024-04-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0015_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registered',
            field=models.BooleanField(default=False),
        ),
    ]
