# Generated by Django 5.1.2 on 2024-10-16 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0019_useraddress_alter_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='home_unit',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='house_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='provinec',
            field=models.CharField(choices=[('آذربایجان شرقی', 'East Azarbaijan'), ('آذربایجان غربی', 'West Azarbaijan'), ('اردبیل', 'Ardabil'), ('اصفهان', 'Isfahan'), ('البرز', 'Alborz'), ('ایلام', 'Ilam'), ('بوشهر', 'Bushehr'), ('تهران', 'Tehran'), ('چهارمحال و بختیاری', 'Chaharmahal and Bakhtiari'), ('خراسان جنوبی', 'South Khorasan'), ('خراسان رضوی', 'Razavi Khorasan'), ('خراسان شمالی', 'North Khorasan'), ('خوزستان', 'Khuzestan'), ('زنجان', 'Zanjan'), ('سمنان', 'Semnan'), ('سیستان و بلوچستان', 'Sistan and Baluchestan'), ('فارس', 'Fars'), ('قزوین', 'Qazvin'), ('قم', 'Qom'), ('کردستان', 'Kurdistan'), ('کرمان', 'Kerman'), ('کرمانشاه', 'Kermanshah'), ('کهگیلویه و بویراحمد', 'Kohgiluyeh and Boyer-Ahmad'), ('گلستان', 'Golestan'), ('گیلان', 'Gilan'), ('لرستان', 'Lorestan'), ('مازندران', 'Mazandaran'), ('مرکزی', 'Markazi'), ('هرمزگان', 'Hormozgan'), ('همدان', 'Hamadan'), ('یزد', 'Yazd')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='post_code',
            field=models.IntegerField(null=True),
        ),
    ]
