# Generated by Django 4.2.6 on 2024-01-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('aw', 'در انطظار تایید'), ('p', 'درحال پردازش'), ('r', 'اماده ارسال از انبار'), ('d', 'تحویل پست داده شده')], default='aw', max_length=2),
        ),
    ]
