# Generated by Django 4.2.6 on 2024-05-09 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Store', '0004_brad_alter_order_status_product_brad'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('aw', 'در انتظار تایید'), ('p', 'درحال پردازش'), ('r', 'اماده ارسال از انبار'), ('d', 'تحویل پست داده شده'), ('do', 'تحویل مشتری داده شد')], max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL),
        ),
    ]
