# Generated by Django 4.2.6 on 2024-06-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_product_quantity_alter_product_brad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, help_text='اسلاگ', null=True),
        ),
    ]
