# Generated by Django 4.2.6 on 2024-06-19 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_brand_remove_product_brad_delete_brad_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Brand',
            field=models.ForeignKey(blank=True, help_text='برند', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='Store.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='دسته بندی', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='Store.category'),
        ),
    ]
