# Generated by Django 4.2.6 on 2024-06-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0011_alter_product_brand_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(help_text='نام', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default='متفرقه/', help_text='اسلاگ', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='Product/category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='متفرقه', help_text='نام', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='متفرقه/', help_text='اسلاگ', max_length=250, unique=True),
        ),
    ]
