# Generated by Django 5.1.2 on 2024-11-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0014_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='confirmed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
