# Generated by Django 5.1.2 on 2024-11-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0015_comment_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
