# Generated by Django 5.1.2 on 2024-11-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0017_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_price',
            field=models.IntegerField(null=True),
        ),
    ]
